package tcpKit

const (
    REGISTER_TYPE_NIL int16 = iota

    REGISTER_TYPE_STRING
    REGISTER_TYPE_STRING_ARRAY

    REGISTER_TYPE_ERROR
    REGISTER_TYPE_ERROR_ARRAY

    REGISTER_TYPE_BOOL
    REGISTER_TYPE_BOOL_ARRAY

    REGISTER_TYPE_INT8
    REGISTER_TYPE_INT8_ARRAY

    REGISTER_TYPE_UINT8
    REGISTER_TYPE_UINT8_ARRAY

    REGISTER_TYPE_INT16
    REGISTER_TYPE_INT16_ARRAY

    REGISTER_TYPE_UINT16
    REGISTER_TYPE_UINT16_ARRAY

    REGISTER_TYPE_INT32
    REGISTER_TYPE_INT32_ARRAY

    REGISTER_TYPE_UINT32
    REGISTER_TYPE_UINT32_ARRAY

    REGISTER_TYPE_INT64
    REGISTER_TYPE_INT64_ARRAY

    REGISTER_TYPE_UINT64
    REGISTER_TYPE_UINT64_ARRAY

    REGISTER_TYPE_INT
    REGISTER_TYPE_INT_ARRAY

    REGISTER_TYPE_UINT
    REGISTER_TYPE_UINT_ARRAY

    REGISTER_TYPE_MAX
)